"use strict";

const NORMAL = 1;
const FIRE = 2;
const WATER = 3;
const GRASS = 4;
const ELECTRIC = 5;
const ICE = 6;
const FIGHTING = 7;
const POISON = 8;
const GROUND = 9;
const FLYING = 10;
const PSYCHIC = 11;
const BUG = 12;
const ROCK = 13;
const GHOST = 14;
const DRAGON = 15;
const DARK = 16;
const STEEL = 17;
const FAIRY = 18;

const NORMAL_EFFECTIVENESS = 0;
const SUPER_EFFECTIVE = 1;
const NOT_VERY_EFFECTIVE = 2;
const IMMUNE = 3;

const EFFECTIVENESS_STRING = new Array(4);
EFFECTIVENESS_STRING[NORMAL_EFFECTIVENESS] = "こうかはふつうだ";
EFFECTIVENESS_STRING[SUPER_EFFECTIVE] = "こうかはばつぐんだ！";
EFFECTIVENESS_STRING[NOT_VERY_EFFECTIVE] = "こうかはいまひとつのようだ";
EFFECTIVENESS_STRING[IMMUNE] = "こうかはないみたいだ...";

const TYPE_NAMES = new Array(18 + 1);
TYPE_NAMES[NORMAL] = "ノーマル";
TYPE_NAMES[FIRE] = "ほのお";
TYPE_NAMES[WATER] = "みず";
TYPE_NAMES[GRASS] = "くさ";
TYPE_NAMES[ELECTRIC] = "でんき";
TYPE_NAMES[ICE] = "こおり";
TYPE_NAMES[FIGHTING] = "ひこう";
TYPE_NAMES[POISON] = "どく";
TYPE_NAMES[GROUND] = "じめん";
TYPE_NAMES[FLYING] = "ひこう";
TYPE_NAMES[PSYCHIC] = "エスパー";
TYPE_NAMES[BUG] = "むし";
TYPE_NAMES[ROCK] = "じめん";
TYPE_NAMES[GHOST] = "ゴースト";
TYPE_NAMES[DRAGON] = "ドラゴン";
TYPE_NAMES[DARK] = "あく";
TYPE_NAMES[STEEL] = "はがね";
TYPE_NAMES[FAIRY] = "フェアリー";

const TYPE_EFFECTIVENESS = new Array(18 + 1);
for (let i = 0; i < TYPE_EFFECTIVENESS.length; i++) {
  TYPE_EFFECTIVENESS[i] = new Array(18 + 1).fill(NORMAL_EFFECTIVENESS);
}

// ノーマル
TYPE_EFFECTIVENESS[NORMAL][FIGHTING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[NORMAL][GHOST] = IMMUNE;

// ほのお
TYPE_EFFECTIVENESS[FIRE][FIRE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][WATER] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][ICE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][GROUND] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][ROCK] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][STEEL] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIRE][FAIRY] = NOT_VERY_EFFECTIVE;

// みず
TYPE_EFFECTIVENESS[WATER][FIRE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[WATER][WATER] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[WATER][ELECTRIC] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[WATER][GRASS] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[WATER][ICE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[WATER][FIRE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[WATER][STEEL] = NOT_VERY_EFFECTIVE;

// くさ
TYPE_EFFECTIVENESS[GRASS][FIRE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][WATER] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][ELECTRIC] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][ICE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][POISON] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][GROUND] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][FLYING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GRASS][BUG] = SUPER_EFFECTIVE;

// でんき
TYPE_EFFECTIVENESS[ELECTRIC][ELECTRIC] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ELECTRIC][GROUND] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ELECTRIC][FLYING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ELECTRIC][STEEL] = NOT_VERY_EFFECTIVE;

// こおり
TYPE_EFFECTIVENESS[ICE][FIRE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ICE][ICE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ICE][FIGHTING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ICE][ROCK] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ICE][STEEL] = SUPER_EFFECTIVE;

// かくとう
TYPE_EFFECTIVENESS[FIGHTING][FLYING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FIGHTING][PSYCHIC] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FIGHTING][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIGHTING][ROCK] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIGHTING][DARK] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FIGHTING][FAIRY] = SUPER_EFFECTIVE;

// どく
TYPE_EFFECTIVENESS[POISON][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][FIGHTING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][POISON] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][GROUND] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][POISON] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][PSYCHIC] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[POISON][FAIRY] = NOT_VERY_EFFECTIVE;

// じめん
TYPE_EFFECTIVENESS[GROUND][WATER] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GROUND][GRASS] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GROUND][ELECTRIC] = IMMUNE;
TYPE_EFFECTIVENESS[GROUND][ICE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GROUND][POISON] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GROUND][ROCK] = NOT_VERY_EFFECTIVE;

// ひこう
TYPE_EFFECTIVENESS[FLYING][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FLYING][ELECTRIC] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FLYING][ICE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FLYING][FIGHTING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FLYING][GROUND] = IMMUNE;
TYPE_EFFECTIVENESS[FLYING][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FLYING][ROCK] = NOT_VERY_EFFECTIVE;

// エスパー
TYPE_EFFECTIVENESS[PSYCHIC][FIGHTING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[PSYCHIC][PSYCHIC] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[PSYCHIC][BUG] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[PSYCHIC][GHOST] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[PSYCHIC][DARK] = SUPER_EFFECTIVE;

// むし
TYPE_EFFECTIVENESS[BUG][FIRE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[BUG][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[BUG][FIGHTING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[BUG][GROUND] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[BUG][FLYING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[BUG][ROCK] = SUPER_EFFECTIVE;

// いわ
TYPE_EFFECTIVENESS[ROCK][NORMAL] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][FIRE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][WATER] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][GRASS] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][FIGHTING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][POISON] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][GROUND] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][FLYING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[ROCK][STEEL] = SUPER_EFFECTIVE;

// ゴースト
TYPE_EFFECTIVENESS[GHOST][NORMAL] = IMMUNE;
TYPE_EFFECTIVENESS[GHOST][FIGHTING] = IMMUNE;
TYPE_EFFECTIVENESS[GHOST][POISON] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GHOST][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[GHOST][GHOST] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[GHOST][STEEL] = SUPER_EFFECTIVE;

// ドラゴン
TYPE_EFFECTIVENESS[DRAGON][FIRE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[DRAGON][WATER] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[DRAGON][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[DRAGON][ELECTRIC] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[DRAGON][ICE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[DRAGON][DRAGON] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[DRAGON][FAIRY] = SUPER_EFFECTIVE;

// あく
TYPE_EFFECTIVENESS[DARK][FIGHTING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[DARK][PSYCHIC] = IMMUNE;
TYPE_EFFECTIVENESS[DARK][BUG] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[DARK][GHOST] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[DARK][DARK] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[DARK][FAIRY] = SUPER_EFFECTIVE;

// はがね
TYPE_EFFECTIVENESS[STEEL][NORMAL] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][FIRE] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][GRASS] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][ICE] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][FIGHTING] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][POISON] = IMMUNE;
TYPE_EFFECTIVENESS[STEEL][GROUND] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][FLYING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][PSYCHIC] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][ROCK] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][DRAGON] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][STEEL] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[STEEL][FAIRY] = NOT_VERY_EFFECTIVE;

// フェアリー
TYPE_EFFECTIVENESS[FAIRY][FIGHTING] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FAIRY][POISON] = SUPER_EFFECTIVE;
TYPE_EFFECTIVENESS[FAIRY][BUG] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FAIRY][DRAGON] = IMMUNE;
TYPE_EFFECTIVENESS[FAIRY][DARK] = NOT_VERY_EFFECTIVE;
TYPE_EFFECTIVENESS[FAIRY][STEEL] = SUPER_EFFECTIVE;

// 防御側のタイプ
let defendingType;
// 攻撃側のタイプ
let attackingType;

(function () {
  // 攻撃ボタンを追加
  const attackingButtons = document.getElementById("attacking-buttons");
  for (var i = 1; i <= 18; i++) {
    let button = document.createElement("button");
    button.id = "attacking-" + i;
    button.value = i;
    button.style = "flex-basis: 100px;";
    button.onclick = function () {
      attack(this.value);
    };

    let img = document.createElement("img");
    img.src = "img/icon_type_" + i + "_on.svg";
    img.style =
      "display: block; width: 48px; height: 48px; margin: 0 auto 8px;";
    button.appendChild(img);

    let label = document.createElement("span");
    label.innerText = TYPE_NAMES[i];
    button.appendChild(label);

    attackingButtons.appendChild(button);
    attackingButtons.appendChild;
  }

  // リセットボタン
  const resetButton = document.getElementById("reset-button");
  resetButton.onclick = function () {
    reset();
  };

  reset();
})();

function reset() {
  defendingType = Math.floor(Math.random() * 18) + 1;

  const defendingImg = document.getElementById("defending-img");
  defendingImg.src = "./img/icon_type_" + defendingType + "_on.svg";

  const defendingLabel = document.getElementById("defending-label");
  defendingLabel.innerText = TYPE_NAMES[defendingType];

  attackingType = null;
  setResult("");
}

function attack(type) {
  attackingType = type;
  setResult(
    EFFECTIVENESS_STRING[TYPE_EFFECTIVENESS[defendingType][attackingType]]
  );
}

function setResult(text) {
  const result = document.getElementById("result");
  result.innerText = text;
}
